#
# (C) Copyright 2018
#

#EXTRA_CFLAGS = -Idrivers/video/include/

obj-y += hdmitx.o

hdmitx-y := hdmitx_set.o hdmitx_tvenc.o enc_clk_config.o hdmi_edid_parsing.o hdmi_parameters.o
#aml_hdmitx20-$(CONFIG_AML_HDMITX20_HDCP) += hdmitx_hdcp.o

