# SPDX-License-Identifier: GPL-2.0+

obj-y					+= pinctrl-meson.o
obj-$(CONFIG_PINCTRL_MESON8_PMX)	+= pinctrl-meson8-pmx.o
obj-$(CONFIG_PINCTRL_MESON_AXG_PMX)	+= pinctrl-meson-axg-pmx.o
obj-$(CONFIG_PINCONF_MESON_G12A)	+= pinconf-meson-g12a.o
obj-$(CONFIG_PINCTRL_MESON_GXBB)	+= pinctrl-meson-gxbb.o
obj-$(CONFIG_PINCTRL_MESON_GXL)		+= pinctrl-meson-gxl.o
obj-$(CONFIG_PINCTRL_MESON_AXG)		+= pinctrl-meson-axg.o
obj-$(CONFIG_PINCTRL_MESON_G12A)	+= pinctrl-meson-g12a.o
