
/*SPIFC*/
#define SPIFC_AHB_REQ_CTRL				PREG_STICKY_REG0
#define SPIFC_AHB_REQ_CTRL1				PREG_STICKY_REG0
#define SPIFC_AHB_REQ_CTRL2				PREG_STICKY_REG0
#define SPIFC_USER_DBUF_ADDR			PREG_STICKY_REG0
#define SPIFC_AHB_CTRL       			PREG_STICKY_REG0
#define CLKTREE_SPIFC_CLK_CTRL 			PREG_STICKY_REG0
#define SPIFC_ACTIMING0      			PREG_STICKY_REG0
#define SPI_ADDR_BASE      			    PREG_STICKY_REG0

#define PADCTRL_GPIOB_DS   			    PREG_STICKY_REG0
#define PADCTRL_PIN_MUX_REG3		    PREG_STICKY_REG0
#define PADCTRL_PIN_MUX_REG4		    PREG_STICKY_REG0
#define PADCTRL_PIN_MUX_REG5		    PREG_STICKY_REG0
#define PADCTRL_GPIOC_DS     		    PREG_STICKY_REG0
#define PADCTRL_GPIOC_OEN     		    PREG_STICKY_REG0
#define PADCTRL_GPIOC_PULL_EN 		    PREG_STICKY_REG0
#define PADCTRL_GPIOC_PULL_UP 		    PREG_STICKY_REG0
#define PADCTRL_GPIOC_I     		    PREG_STICKY_REG0
#define SYSCTRL_SEC_STATUS_REG4         PREG_STICKY_REG0

#define CPUCTRL_CTRL2                   PREG_STICKY_REG0
#define CPUCTRL_RESET_CTRL              PREG_STICKY_REG0

#define SYSCTRL_DEBUG_REG5              PREG_STICKY_REG0

#define SYSCTRL_SEC_STICKY_REG1         PREG_STICKY_REG0

#define SYSCTRL_SEC_STATUS_REG15        PREG_STICKY_REG0
#define SYSCTRL_SEC_STATUS_REG16        PREG_STICKY_REG0
#define SYSCTRL_SEC_STATUS_REG17        PREG_STICKY_REG0

#define HHI_VPU_MEM_PD_REG4             PREG_STICKY_REG0

#define UART_B_WFIFO                    ((0x8c00  << 2) + 0xffd00000)
