#
# (c) Copyright 2018
# AmLogic Nand Flash Controller Driver
# Author: Xianjun Liu <xianjun.liu@amlogic.com>
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-$(CONFIG_MESON_NFC) += aml_nand.o meson_nand.o nand_flash.o cmd_amlmtd.o boot.o storage_nand.o

