ifdef CONFIG_AVB2_KPUB_DEFAULT_VENDOR
PLATFORM_CPPFLAGS += -DCONFIG_AVB2_KPUB_DEFAULT_VENDOR=1
PLATFORM_CPPFLAGS += -DCONFIG_AVB2_KPUB_VENDOR=1
endif

ifdef CONFIG_AVB2_KPUB_VENDOR
PLATFORM_CPPFLAGS += -DCONFIG_AVB2_KPUB_VENDOR=1
endif
