# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_AML_MEDIA) += media/

obj-$(CONFIG_UNIFY_KEY_MANAGE) += keymanage/

obj-$(CONFIG_SECURE_STORAGE) += storagekey/

obj-$(CONFIG_SECURE_POWER_CONTROL) += power/

obj-$(CONFIG_MESON_LEDS_STATE_CONTROL) += leds/

obj-$(CONFIG_MESON_IR) += ir/

obj-$(CONFIG_AMLOGIC_TEE) += tee/

obj-$(CONFIG_AML_CRYPTO) += crypto/

obj-$(CONFIG_AML_MKL) += mkl/
