# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_AML_MEDIA) += media/

obj-$(CONFIG_UNIFY_KEY_MANAGE) += keymanage/

obj-$(CONFIG_SECURE_STORAGE) += storagekey/

obj-$(CONFIG_SECURE_POWER_CONTROL) += power/

obj-$(CONFIG_MESON_LEDS_STATE_CONTROL) += leds/
