
obj-y += aml_v3_common.o

aml_v3_common-y += v3_tool_buff_manager.o
aml_v3_common-y += v3_tool_simg2img.o
aml_v3_common-y += v3_tool_media.o
ifndef CONFIG_AML_V2_FACTORY_BURN
aml_v3_common-y += ../../v2_burning/v2_common/optimus_progress.o
endif

