obj-$(CONFIG_AML_LCD_BL_LOCAL_DIMMING) += ldim_drv.o ldim_dev_drv.o ldim_spi.o ldim_global.o
obj-$(CONFIG_AML_LCD_BL_LOCAL_DIMMING_IW7027) += iw7027.o
obj-$(CONFIG_AML_LCD_BL_LOCAL_DIMMING_OB3350) += ob3350.o
