obj-$(CONFIG_AML_LCD_BL_LDIM) += ldim_drv.o ldim_dev_drv.o ldim_spi.o global.o
obj-$(CONFIG_AML_LCD_BL_LDIM_IW7027) += iw7027.o
obj-$(CONFIG_AML_LCD_BL_LDIM_OB3350) += ob3350.o
obj-$(CONFIG_AML_LCD_BL_LDIM_BLMCU) += blmcu.o
