obj-$(CONFIG_AML_LCD) += lcd_vout.o lcd_common.o lcd_gpio.o \
		lcd_clk_config.o lcd_phy_config.o lcd_debug.o \
		lcd_unifykey.o lcd_i2c_dev.o lcd_init_test.o lcd_vbyone.o

obj-$(CONFIG_AML_LCD) += lcd_venc/
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon.o lcd_tcon_hw.o lcd_tcon_spi.o
obj-$(CONFIG_AML_LCD_TV) += lcd_tv/
obj-$(CONFIG_AML_LCD_TABLET) += lcd_tablet/
obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern/
obj-$(CONFIG_AML_LCD_BACKLIGHT) += backlight/
