obj-$(CONFIG_AML_LCD) += lcd_vout.o lcd_common.o lcd_clk_config.o \
		lcd_bl.o lcd_unifykey.o lcd_debug.o lcd_tcon.o
obj-$(CONFIG_AML_LCD_TV) += lcd_tv/
obj-$(CONFIG_AML_LCD_TABLET) += lcd_tablet/
obj-$(CONFIG_AML_LCD_EXTERN) += lcd_extern/
obj-$(CONFIG_AML_BL_LOCAL_DIMMING) += bl_ldim/
obj-$(CONFIG_AML_BL_EXTERN) += bl_extern/
