# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2006
#
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_SPI_NAND) += aml_spinand.o
obj-$(CONFIG_AML_STORAGE) += storage_sn.o
