obj-$(CONFIG_AML_LCD) += lcd_phy_if.o
obj-$(CONFIG_AML_LCD) += lcd_phy_utils.o
obj-$(CONFIG_AML_LCD) += lcd_phy_c3.o
obj-$(CONFIG_AML_LCD) += lcd_phy_g12a.o
obj-$(CONFIG_AML_LCD) += lcd_phy_t3_t5m.o
obj-$(CONFIG_AML_LCD) += lcd_phy_t5_t5d_t5w.o
obj-$(CONFIG_AML_LCD) += lcd_phy_t7.o
obj-$(CONFIG_AML_LCD) += lcd_phy_tl1.o
