/mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/board/amlogic/g12b_w400_v1/firmware/acs_entry.o: \
 acs_entry.S \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/config.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/config_defaults.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/config_uncmd_spl.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/configs/g12b_w400_v1.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/arch/arm/include/asm/arch/cpu.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/arch/arm/include/asm/config.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/linux/kconfig.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/generated/autoconf.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/config_fallbacks.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/generated/autoconf.h \
 /mnt/fileroot/xiaobo.gu/work/uboot/repo-bootloader/v2018/bl33/include/generated/version_autogenerated.h
