#
# Copyright (c) 2018 Amlogic Electronics Co., Ltd
#
# SPDX-License-Identifier:      GPL-2.0+
#
obj-$(CONFIG_CLK_MESON) += clk.o
obj-$(CONFIG_CLK_MESON_G12A) += clk_meson_g12a.o
obj-$(CONFIG_CLK_MESON_G12B) += clk_meson_g12b.o
