#
# Copyright (c) 2018 Amlogic Electronics Co., Ltd
#
# SPDX-License-Identifier:      GPL-2.0+
#
obj-$(CONFIG_CLK_MESON) += clk.o
obj-$(CONFIG_CLK_MESON_G12) += clk_meson_g12.o clk_measure.o
obj-$(CONFIG_CLK_MESON_A1) += clk_meson_a1.o clk_measure.o
obj-$(CONFIG_CLK_MESON_C1) += clk_meson_c1.o clk_measure.o
obj-$(CONFIG_CLK_MESON_S4) += clk_meson_s4.o clk_measure.o
obj-$(CONFIG_CLK_MESON_SC2) += clk_meson_sc2.o clk_measure.o
obj-$(CONFIG_CLK_MESON_C2) += clk_meson_c2.o clk_measure.o
