obj-$(CONFIG_AML_LCD_TABLET) += DP_aux.o
obj-$(CONFIG_AML_LCD_TABLET) += DP_EDID.o
obj-$(CONFIG_AML_LCD_TABLET) += DP_timing.o
obj-$(CONFIG_AML_LCD_TABLET) += DP_training.o
obj-$(CONFIG_AML_LCD_TABLET) += DP_utils.o
obj-$(CONFIG_AML_LCD_TABLET) += DP_debug.o

obj-$(CONFIG_AML_LCD_TABLET) += DP_tx.o

obj-$(CONFIG_AML_LCD_TABLET) += lcd_eDP.o
