#ifndef __MESON_SARADC_H__
#define __MESON_SARADC_H__

#include <adc.h>

enum ADC_CHANNEL_TYPE {
	MESON_SARADC_CH0 = 0,
	MESON_SARADC_CH1,
	MESON_SARADC_CH2,
	MESON_SARADC_CH3,
	MESON_SARADC_CH4,
	MESON_SARADC_CH5,
	MESON_SARADC_CH6,
	MESON_SARADC_CH7,
	MESON_SARADC_CH_MAX,
};

#define SARADC_CH_SELF_TEST MESON_SARADC_CH7

#endif /*_MESON_SARADC_H_*/
