#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_AML_NAND) += aml_nand_logic.o

aml_nand_logic-objs += aml_nftl_cache.o aml_nftl_common.o aml_nftl_create_list.o aml_nftl_gc.o aml_nftl_init.o aml_nftl_interface.o aml_nftl_list.o aml_nftl_logic.o aml_nftl_start.o aml_phyops.o