/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __SC2_DEF_H__
#define __SC2_DEF_H__

#include "secure_apb.h"


#define SEC_SYS_CPU_CFG2		CPUCTRL_SYS_CPU_CFG2

#define SEC_AO_SEC_GP_CFG0	SYSCTRL_SEC_STATUS_REG4
#define SEC_AO_SEC_GP_CFG2	SYSCTRL_SEC_STATUS_REG6
#define SEC_AO_SEC_GP_CFG3	SYSCTRL_SEC_STATUS_REG15
#define SEC_AO_SEC_GP_CFG4	SYSCTRL_SEC_STATUS_REG16
#define SEC_AO_SEC_GP_CFG5	SYSCTRL_SEC_STATUS_REG17
#define SEC_AO_SEC_GP_CFG7	SYSCTRL_SEC_STATUS_REG2
#define SEC_AO_SEC_GP_CFG8	SYSCTRL_SEC_STATUS_REG10
#define SEC_AO_SEC_GP_CFG9	SYSCTRL_SEC_STATUS_REG11


#define AO_SEC_GP_CFG8	SYSCTRL_SEC_STATUS_REG10
#define AO_SEC_GP_CFG9	SYSCTRL_SEC_STATUS_REG11
#define SEC_AO_SEC_SD_CFG15	SYSCTRL_SEC_STATUS_REG31

#define SEC_AO_RTI_STATUS_REG3		SYSCTRL_SEC_STICKY_REG1


#define AO_SEC_SD_CFG15 SEC_AO_SEC_SD_CFG15

#endif /* __SC2_DEF_H__ */
