# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_AML_SPI_NFC) += spi_nfc.o nfc.o
obj-$(CONFIG_AML_SPIFC) += spifc.o
obj-$(CONFIG_AML_SPIFCV2) += spifc_v2.o
obj-$(CONFIG_AML_SPICC) += spicc.o
obj-$(CONFIG_AML_SPICCV2) += spicc_v2.o
obj-$(CONFIG_DM_SPI) += page_info.o
