#
# (C) Copyright 2020
#

#EXTRA_CFLAGS = -Idrivers/video/include/

obj-y += hdmitx21.o

hdmitx21-y := hdmitx_drv.o hdmitx_tvenc.o hdmitx_infoframe.o hdmitx_pktmgmt.o hdmitx_dump.o
hdmitx21-y += hdmi_edid_parsing.o hdmi_param.o hdmi.o
